### ISSUE TITLE
regression: The option `hardware.amdgpu' does not exist

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixos-hardware#1023]
starting from 2312742, loading module `nixos-hardware.nixosModules.lenovo-ideapad-slim-5` yields:

```
error: The option `hardware.amdgpu' does not exist
```

this seems to relate to that commit's removal of `options.hardware.amdgpu.loadInInitrd`.

**Comment by KiaraGrouwstra** [comment]
maybe i should read better and update nixpkgs too

**Comment by johnhamelink** [comment]
For me, I had to upgrade nixpkgs from 24.05 to nixpkgs-unstable - I haven't seen nixpkgs-unstable as a prerequisite in the docs?

**Comment by Mic92** [comment]
Not it also works with 24.05 as you can see from our CI tests, but you need to update 24.05 to a newer version.
