### ISSUE TITLE
Should fwupd be (mkDefault) enabled, or only included in the README ?

### ISSUE THREAD

**Issue by matdibu** [NixOS/nixos-hardware#1159]
Some configs enable it, others write about it. What's the best way to go about it?
- enabled in config
- mentioned in readme
- leave it as-is, sometimes in config sometimes in readme

**Comment by SuperSandro2000** [comment]
If the device has proper support from the manufacturer for it, sure why not? Most devices I own myself have barely more than the uefi dbx list where enabling fwupd is a bit pointless if we are honest.

**Comment by matdibu** [comment]
so if a device supports fwupd (for more than uefi dbx), it's recommended for the nixos-hardware config to enable it, got it
