### ISSUE TITLE
Support for Lenovo Slim 7x Qualcomm X-Elite

### ISSUE THREAD

**Issue by eureka-cpu** [NixOS/nixos-hardware#1169]
Linux support is still under development, but at least confirmed working somewhat [here](https://gist.github.com/joske/52be3f1e5d0239706cd5a4252606644b). It's a beautiful laptop, would be awesome to get NixOS running smoothly on it. Plus, who can resist that battery life? 🙂

**Comment by eureka-cpu** [comment]
Also Phoronix claims support in the mainline linux kernel is already here https://www.phoronix.com/news/Linux-6.11-SoC-Platforms 😄

**Comment by eureka-cpu** [comment]
Testing this out today since my yoga just came in! https://github.com/kuruczgy/x1e-nixos-config

**Comment by Mic92** [comment]
Sounds good to me. Just make a pull request.
