### ISSUE TITLE
Recent VAAPI change to comon/gpu/intel breaks existing configs

### ISSUE THREAD

**Issue by domtoro** [NixOS/nixos-hardware#1170]
Hey 👋,

While updating an existing NixOS system with the most recent nixos-hardware version, I encountered a collision error involving the intel-vaapi-driver during the opengl-drivers build process:

```
opengl-drivers> building '/nix/store/58gwk9yz7rswvafq5wa9w34s6pmfx9zg-opengl-drivers.drv'
opengl-drivers> error: collision between `/nix/store/l2lsws9wvzwg4xb3chcwblx6i1vahx1m-intel-vaapi-driver-2.4.1/lib/dri/i965_drv_video.so' and `/nix/store/zw9g7llgjid3j2x038c5yylwxmwbm99a-intel-vaapi-driver-2.4.1/lib/dri/i965_drv_video.so'
error: builder for '/nix/store/58gwk9yz7rswvafq5wa9w34s6pmfx9zg-opengl-drivers.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/l2lsws9wvzwg4xb3chcwblx6i1vahx1m-intel-vaapi-driver-2.4.1/lib/dri/i965_drv_video.so' and `/nix/store/zw9g7llgjid3j2x038c5yylwxmwbm99a-intel-vaapi-driver-2.4.1/lib/dri/i965_drv_video.so'
```

A quick test indicates that this issue was introduced with commit 7200fdc70facade9676f8548de37ab23f71a4687.
Rolling back nixos-hardware to the commit before that allows for a successful rebuild.

Relevant excerpt from the systems config (`24.05.5366.fbca5e745367 (Uakari)`):
```nix
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      # Intel iGPU firmware
      intel-media-driver
      intel-vaapi-driver
    ];
  };
```
As far as I can tell there is nothing else relating to this in the config

Cheers!

@Pandapip1

**Comment by Pandapip1** [comment]
That would be because of the `.override { enableHybridCodec = true; }` part that was added. Just remove `intel-vaapi-driver` from your `hardware.opengl.extraPackages`; it was added there by `nixos-hardware` anyway.
