### ISSUE TITLE
Allow disabling `tiny-dfr`

### ISSUE THREAD

**Issue by reidlabwastaken** [NixOS/nixos-hardware#1171]
by default, the t2 macbook modules force-install a service for the touchbar (tiny-dfr), but, this can make t2 chip based systems that do not have a touchbar have very long build times, for something you don't even use!

it would be great to see an option to easily disable this service for systems without a touchbar ❤️

**Comment by Mic92** [comment]
Ok. Just add nixos option in the profile to disable it than.
