### ISSUE TITLE
`ssd.nix`:`fstrim` should not be enabled by default and only activated on `ext4` filesystems

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixos-hardware#1199]
This is because `btrfs`, `zfs` and `xfs` get automatically mounted with `discard=async` since kernel 6.2.

Right now, this causes those systems to trim with much more frequency, effectively increasing wear.

**Comment by Mic92** [comment]
Much more means here, once per week more. How often does the discard=async effectively run trim?

**Comment by Mic92** [comment]
https://btrfs.readthedocs.io/en/latest/Trim.html

> the tool fstrim starts a trim operation on the whole filesystem, no mount options need to be specified, so it’s up to the filesystem to traverse the free space and start the trim, this is suitable for running it as periodic service

If async discard is enabled, does it still run trim with fstrim?

**Comment by ahydronous** [comment]
`discard` is ran immediately with `sync` and as soon as possible with `async`. `fstrim` is ran whenever it is called upon by a cronjob or systemd.

But digging a bit deeper, it seems SSDs even as recent as the Samsung 800 series still have issues with queued trim commands. So out of caution / as a general rule, it should be the other way around, always `fstrim` and avoid using `discard`. Damn

**Comment by Mic92** [comment]
Ubuntu does the same.
