### ISSUE TITLE
Lenovo Ideapad 5 wrong CPU, GPU

### ISSUE THREAD

**Issue by VictuarVi** [NixOS/nixos-hardware#1203]
My laptop is the **Lenovo IdeaPad Slim 5 16IAH8** and, looking at the module in `lenovo/ideapad/slim-5`, the modules loaded are for AMD CPU and GPU – which I have not; they are: Intel Core i5-12450H and Intel UHD Graphics.

**Comment by Mic92** [comment]
Is it possible that this or a similar model have an AMD version?

**Comment by VictuarVi** [comment]
Yes, other Ideapad Slim 5  (such as [this](https://www.lenovo.com/us/en/p/laptops/ideapad/ideapad-500/lenovo-ideapad-slim-5-gen-9-16-inch-amd/len101i0093t)) have indeed an AMD CPU, though not all of them (such as mine).

**Comment by Mic92** [comment]
Ok. Can you add a pull request that add the AMD version as a variant?

**Comment by VictuarVi** [comment]
Yes, I created #1224 .
