### ISSUE TITLE
Typo in turing configuration file

### ISSUE THREAD

**Issue by onurmercury** [NixOS/nixos-hardware#1214]
https://github.com/NixOS/nixos-hardware/blob/07d15e8990d5d86a631641b4c429bc0a7400cfb8/common/gpu/nvidia/turing/default.nix#L3

**Comment by Mic92** [comment]
Right. Pull requests are welcome.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixos-hardware/pull/1216
