### ISSUE TITLE
Request: Asus Pro Art P16

### ISSUE THREAD

**Issue by thebrianbug** [NixOS/nixos-hardware#1257]
Hi there!

[Link to ASUS page](https://www.asus.com/us/laptops/for-creators/proart/proart-p16-h7606/)

What would be required to add this laptop?

**Comment by Mic92** [comment]
You can probably copy an existing AMD-based laptop and remove the non-model specific parts.
i.e. this one: https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/t14s/amd/default.nix
From there on, there is no recipe. Maybe you need to have a new kernel if it's a new laptop.
Maybe you find fixes needed i.e. in the archlinux wiki to make all the hardware work.
