### ISSUE TITLE
Generated hardware-configuration.nix files use deprecated attribute

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixos-hardware#135]
The generated `hardware-configuration.nix` files still use the now deprecated `i18n.consoleFont` attribute (it should now be `console.font`). Because of this you get warnings such as below

```
trace: warning: The option `i18n.consoleFont' defined in `/etc/nixos/hardware-configuration.nix' has been renamed to `console.font'.
```

**Comment by Mic92** [comment]
This issue should be opened in nixpkgs instead as the script that generates the configuration also lives there.

**Comment by mdedetrich** [comment]
Ticket created at https://github.com/NixOS/nixpkgs/issues/76391
