### ISSUE TITLE
The description of this repo links to this repo

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixos-hardware#15]
Everyone who sees this page will know where it is ;)

**Comment by copumpkin** [comment]
Yeah, seems a little odd 😄

**Comment by primeos** [comment]
This actually confuses me every time...

It feels like being at the wrong place ("Moved to") and like I'm supposed to click that link. Would be nice if we could get rid of it :smile:

And it doesn't blend in with the other descriptions: https://github.com/NixOS

We could change it to "A collection of NixOS modules covering hardware quirks." from the README.md for example :wink:

cc @ehmry

**Comment by ehmry** [comment]
I don't have the rights, methinks it takes a NixOS admin, @garbas ?

**Comment by garbas** [comment]
fixed the description thx @primeos for making me not think what to write :)

@ehmry you should have the admin right for this repo now.
