### ISSUE TITLE
Asus FX504GD: Touchpad stop working suddenly

### ISSUE THREAD

**Issue by ImExtends** [NixOS/nixos-hardware#162]
Hello, I've been using NixOS for a week, but I still have a problem: my touchpad seems to stop working from time to time for almost 3 minutes, and I have this problem like 7 times a day and all I can do is wait until he reworks again. I specified `services.xserver.libinput.enable = true;` in my `/etc/nixos/configuration.nix`, but I still have the same problem. I'm actually using an Asus FX504GD.
Did anybody encouter this issue and knows how to solve the problem ? I would be glad, thanks.

**Comment by ehmry** [comment]
I've seen similar problems with a dell latitude 3480, but no fix.

**Comment by ImExtends** [comment]
> I've seen similar problems with a dell latitude 3480, but no fix.

I've seen another issue with this but no fix, it would be good to have an answer, otherwise I'll have to go with another distro unfortunately 😕

**Comment by ehmry** [comment]
Do you know that the touchpad works with other distros?

**Comment by ImExtends** [comment]
> Do you know that the touchpad works with other distros?

Yup, I was on Arch Linux for 6-7 months and no problem with that

**Comment by Moredread** [comment]
Some profiles blacklist the psmouse module (I think), is that loaded on your systems?

**Comment by ImExtends** [comment]
How can I see if he is loaded?

**Comment by ehmry** [comment]
`lsmod | grep psmouse`

**Comment by ImExtends** [comment]
> `lsmod | grep psmouse`
> 
> 

Yeah it returns nothing

**Comment by ImExtends** [comment]
No real fix, I had to reinstall it completely to make the touchpad work correctly

**Comment by Moredread** [comment]
What did you reinstall?

**Comment by ImExtends** [comment]
> What did you reinstall?

I didn't know how to resolve the problem, didn't find anything on internet. Plus, I had others problems including this

**Comment by Mic92** [comment]
Maybe it got fixed by a kernel upgrade.
