### ISSUE TITLE
Lenovo Thinkpad T14 AMD Gen 1

### ISSUE THREAD

**Issue by sevenfourk** [NixOS/nixos-hardware#205]
Do you think we need a separate profile or we can use this one:

https://github.com/NixOS/nixos-hardware/tree/master/lenovo/thinkpad/t14s/amd/gen1 ?

**Comment by Mic92** [comment]
They seem fairly similar. Maybe we could just symlink t14s to t14? There is an intel version for t14s in addition.

**Comment by sevenfourk** [comment]
yes, i guess symlink is perfect at this time.

they both come in intel/amd versions.

but hardware itself should be identical. 

will update it.
