### ISSUE TITLE
apple/macbook-pro/12-1: wireless don't get reconnected after resume

### ISSUE THREAD

**Issue by sevenfourk** [NixOS/nixos-hardware#210]
not sure what to add here, but wanted to at least file an issue as a todo item.

hardware: 03:00.0 Network controller: Broadcom Inc. and subsidiaries BCM43602 802.11ac Wireless LAN SoC (rev 01)

**Comment by Mic92** [comment]
Is this something to inform Linux upstream about? Also which kernel version and is it fixed by `rmmod $yourwifidriver && modprobe $yourwifidriver` where you network driver probably has something like bcm or broadcom in its name.

**Comment by sevenfourk** [comment]
normally wifi does not get crashed or so, just does not get started.

so i did a plain `restart wpa_supplicant.service`. when i used arch i remember (driver crashed) doing unload/load and then doing a restart.
