### ISSUE TITLE
NVIDIA Jetson Nano and Xavier NX support

### ISSUE THREAD

**Issue by danmx** [NixOS/nixos-hardware#219]
I'm still starting with NixOS but I find it very useful to have a declarative system configuration. I saw that it's possible to build custom NixOS images using [nixos-build and hydra](https://nixos.mayflower.consulting/blog/2018/09/11/custom-images/).

Since NVIDIA provides its [JetPack SDK](https://developer.nvidia.com/embedded/jetpack) Ubuntu-based image. Would it be possible to convert it to NixOS?

**Comment by Mic92** [comment]
Maybe @samueldr can help out here on how to port NixOS to this device.

**Comment by blakat360** [comment]
I would also be interested in knowing how to do this.

**Comment by samueldr** [comment]
I have no information about NVIDIA hardware other than "third party" data.

AFAIUI they use a custom boot chain, which makes things harder to port.

And AFAICT there might be enough relevant differences in the different NVIDIA platforms that solving it for one wouldn't be enough for the others. Though take this with a grain of salt, I'm working from a flawed **superficial** understanding.

Sadly without the hardware to look at, prod and poke, there's likely nothing I can really do.

**Comment by blakat360** [comment]
@samueldr I'd be happy to send you over a nano to play with if that would help?

**Comment by samueldr** [comment]
Only if you were able to send *time* along with it. Sadly it would likely sit unchecked like some other things I acquired for my own use...

I don't really have the free time to look at this *on top* of everything else I'm doing, sorry :/...

**Comment by danmx** [comment]
Is it possible to get NVIDIA's kernel and bootloader with just NixOS' userspace?

**Comment by Mic92** [comment]
@danmx Yes. You can build nixos images without kernel/initrd. Here an example:

This builds an ext4 image: https://github.com/Mic92/vmsh/blob/main/nix/nixos-image.nix 
And here is the corresponding nixos configuration that builds an init executable that you can boot from:
https://github.com/Mic92/vmsh/blob/d8ac04fc856c08a98021d1afd9287542eeb2eeb9/nix/modules/configuration.nix#L15

This is an example how you can boot it with qemu: https://github.com/Mic92/vmsh/blob/d8ac04fc856c08a98021d1afd9287542eeb2eeb9/justfile#L137

**Comment by blakat360** [comment]
@Mic92 please do. How do we proceed?

**Comment by Mic92** [comment]
> @samueldr I'd be happy to send you over a nano to play with if that would help?

If this over is still valid and it arrives before I go on Christmas holiday, I would try to get it running. I would probably go for the low hanging fruit by re-using their kernel/boot loader and only provide the nixos userland. In case you are still interested you can reach me at @mic92:nixos.dev on matrix.

**Comment by blakat360** [comment]
do you have discord?

**Comment by Mic92** [comment]
Yes. Mic92#0022 in the nixos discord channel.

**Comment by kjeremy** [comment]
I'm curious if anyone had a chance to play with this.

**Comment by Mic92** [comment]
Nope. Still don't have it.

**Comment by RyzeNGrind** [comment]
I have a NVIDIA Jetson AGX Xavier 32GB and would be interested in contributing towards the development and deployment of NixOS on the NVIDIA Jetson SDK Based Ubuntu image, if there are others interested perhaps we could collaborate on our NVIDIA findings? I currently have a cluster of arm64 RPI4s that will be running NixOS soon as well.

**Comment by danielfullmer** [comment]
Hey all, I've been able to open-source (jetpack-nixos)[https://github.com/anduril/jetpack-nixos], which is a module that enables NixOS to run on Nvidia Jetson devices.

Announcement post: https://discourse.nixos.org/t/jetpack-nixos-nixos-module-for-nvidia-jetson-devices/23632

This includes the Xavier AGX, Xavier NX, and Orin AGX, but unfortunately not the Jetson Nano, since support was dropped by Nvidia in the latest Jetpack release.

**Comment by Mic92** [comment]
I think this project is than good enough. We could potentially integrate this into nixos-hardware but if the author prefers to keep it seperate that's also fine.

**Comment by danielfullmer** [comment]
I'm certainly open to merging this into nixos-hardware (or potentially nixpkgs itself--to unify CUDA packaging).  But, I think we should wait and look again when Jetpack 6 is released (planned to be Q3 2023):

From https://forums.developer.nvidia.com/t/jetson-software-roadmap-for-2023/238889
> Outlined in last year’s roadmap announcement, NVIDIA will finish upstreaming Jetson support to the Linux Kernel by JetPack 6 and pave the way for greater choice of Linux based distributions on Jetson.

**Comment by ShalokShalom** [comment]
> I'm certainly open to merging this into nixos-hardware (and parts of it to nixpkgs itself--to unify CUDA packaging). But, I think we should wait and look again when Jetpack 6 is released (planned to be Q3 2023):
> 
> From https://forums.developer.nvidia.com/t/jetson-software-roadmap-for-2023/238889
> 
> > Outlined in last year’s roadmap announcement, NVIDIA will finish upstreaming Jetson support to the Linux Kernel by JetPack 6 and pave the way for greater choice of Linux based distributions on Jetson.

Sorry, you can clear me up: How is waiting for JetPack 6 helping, when 5 already dropped support?

**Comment by danielfullmer** [comment]
What are you referring to specifically? The Jetson Nano? TX2? If so, you're right, waiting for Jetpack 6 would not help those devices because NVIDIA dropped support in Jetpack 5.  Jetpack 6 would only affect Orin devices.

I should mention, however, that there is some level of support for Tegra devices in the mainline Linux kernel. I know someone who has booted NixOS w/ a mainline kernel on a TX2 devkit and has tested pcie and ethernet as working there.  Obviously CUDA would be unlikely to work, but NVDEC for Tegra is in the mainline kernel: https://www.phoronix.com/news/NVIDIA-Tegra-Linux-5.16-NVDEC

**Comment by mariobaldini** [comment]
Hi Folks, 

I'm also interested on this (specially for jetson nano). 
Anyone still working on it so I could try to collaborate? 

Thanks
