### ISSUE TITLE
add module for RTL8812BU|RTL8822BU (TP-Link wifi usb dongles)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-hardware#239]
https://github.com/morrownr/88x2bu

>Linux Driver for USB WiFi Adapters that are based on the RTL8812BU and RTL8822BU Chipsets 

Can I just add the package here or do I need to add it to nixpkgs first?

**Comment by Mic92** [comment]
If it is just a driver add it to nixpkgs.

**Comment by Mic92** [comment]
Does this answer your question?
