### ISSUE TITLE
dell/xps/15-9560: add

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-hardware#24]
http://grahamc.com/blog/nixos-on-dell-9560

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixos-hardware/blob/master/dell/xps-15-9550.wiki overlaps a good bit. CC @grahamc.

**Comment by boothead** [comment]
Is this still a thing? I came across an issue that took my 9560 offline for a couple of months. The fix ended up being a couple of kernel flags. Is this the best place to add that info? cc @grahamc

**Comment by grahamc** [comment]
Sure, can’t hurt to put it here.

**Comment by Mic92** [comment]
Done here: https://github.com/NixOS/nixos-hardware/tree/master/dell/xps/15-9560
