### ISSUE TITLE
recent nixos master fails to build due to tlp setting

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-hardware#260]
See https://github.com/NixOS/nixpkgs/pull/97972#issuecomment-834774554

Not sure if this should be solved here or in nixpkgs.

**Comment by Mic92** [comment]
Maybe would enable `config.services.tlp.enable` only if `services.power-profiles-daemon.enable ` is not enabled?

**Comment by Mic92** [comment]
Right now this is only an issue if the user has enabled power-profiles-daemon them-self, right?

**Comment by terlar** [comment]
That is partly true, or if they are using something that enables it, for example GNOME. Found in the linked issue:
https://github.com/NixOS/nixpkgs/commit/316928e8c15994053fb72252418d2b3197cb5dc1

I am one of the latter and not sure I would have figured it out without these two issues.

**Comment by benley** [comment]
Pretty sure this is fixed by #263
