### ISSUE TITLE
Thinkpad t14s AMD: amdgpu module? 

### ISSUE THREAD

**Issue by cwyc** [NixOS/nixos-hardware#267]
Would it make sense to import the [/common/gpu/amd](https://github.com/NixOS/nixos-hardware/blob/master/common/gpu/amd/default.nix) module in the [Thinkpad T14s AMD config](https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/t14s/amd/default.nix)?

**Comment by Mic92** [comment]
I guess so. The amd gpu modules was added after the t14s configuration.
