### ISSUE TITLE
New services.tlp.enable default on 20.09

### ISSUE THREAD

**Issue by pnelson** [NixOS/nixos-hardware#268]
PR #263 introduced a new `services.tlp.enable` default that depends on `services.power-profiles-daemon.enable` only available on unstable or the upcoming 21.05 stable. I've resolved this for myself by explicitly setting `services.tlp.enable = true` but I'm wondering if there is a way to only depend on `services.power-profiles-daemon.enable` if that option is available so it doesn't break updates for others.

**Comment by Mic92** [comment]
Yes. I have a look.
