### ISSUE TITLE
Bad source for surface go wifi

### ISSUE THREAD

**Issue by ursi** [NixOS/nixos-hardware#288]
https://github.com/NixOS/nixos-hardware/blob/41775780a0b6b32b3d32dcc32bb9bc6df809062d/microsoft/surface/firmware/surface-go/ath10k/ath10k-replace.nix#L5

^ this doesn't exist

https://github.com/NixOS/nixos-hardware/blob/41775780a0b6b32b3d32dcc32bb9bc6df809062d/microsoft/surface/repos.nix#L10-L15

https://github.com/kvalo/ath10k-firmware/tree/84b47062aab31d67156e0a3ef593a6999a12864b

**Comment by samueldr** [comment]
cc @mexisme who contributed this.

**Comment by mexisme** [comment]
Thanks.
Will try to look tonight; I have an idea what may have happened.

**Comment by ursi** [comment]
I take it this has been fixed?

**Comment by Mic92** [comment]
> I take it this has been fixed?

see https://github.com/NixOS/nixos-hardware/pull/374 maybe you can push the fix over the finish line.

**Comment by Mic92** [comment]
fixed.
