### ISSUE TITLE
Surface Pro 4 touchscreen not working, kernel update should fix

### ISSUE THREAD

**Issue by CTech-BentonE** [NixOS/nixos-hardware#289]
I'm getting this issue exactly: https://github.com/linux-surface/linux-surface/issues/407. Based on the last two comments in that thread, it looks like the solution is to update the kernel. We are on 5.10.19 and they reported resolution when going from 5.10.x to 5.11.x. 

@mexisme can you do this?

**Comment by BentonEdmondson** [comment]
Meant to post that with this account

**Comment by mexisme** [comment]
> I'm getting this issue exactly: [linux-surface/linux-surface#407](https://github.com/linux-surface/linux-surface/issues/407). Based on the last two comments in that thread, it looks like the solution is to update the kernel. We are on 5.10.19 and they reported resolution when going from 5.10.x to 5.11.x.
> 
> @mexisme can you do this?

I can look into upgrading the kernel version tonight.
It looks like the latest patches target 5.12.14, so I'll try for that.

**Comment by devins2518** [comment]
@mexisme any status on this? I've been facing some issues where shutdown hangs after a suspend so I'm hoping this update might fix it

**Comment by mexisme** [comment]
> @mexisme any status on this? I've been facing some issues where shutdown hangs after a suspend so I'm hoping this update might fix it

I'm working on it.  (The job has taken a lot of my time over the last month).

I have a custom 5.11 working on my Surface Go, but that has the `iptsd` settings removed to make it work, so might not be appropriate.
I don't have access to any other Surface hardware any longer, so it might need some testing from others before it can be merged.

**Comment by Flameopathic** [comment]
I am having this issue on my Surface Pro 7. I am working on figuring out a fix for it, and my current idea is to try the version of iptsd on `unstable`, but there is no way that i can find to override `nixpkgs`, which might continue to be an issue because `services.iptsd` does not have a `package` option. thoughts?
