### ISSUE TITLE
Dell XPS 9700 (17) Support

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nixos-hardware#290]
Audio does not currently work, and would seem to require some specialized configuration.
See https://github.com/NixOS/nixpkgs/issues/130882

Would be nice to have some working config for this machien as well.

**Comment by Mic92** [comment]
Just make a PR if you get something running. It is unlikely that someone has the hardware and just makes the PR based on the fact that this issue exists.

**Comment by IvanMalison** [comment]
I did see #291
