### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by Nichlas** [NixOS/nixos-hardware#33]
When I try to add Thinkpad T410 to my config i get the error: `error: undefined variable ‘mkDefault’ at /nix/var/nix/profiles/per-user/root/channels/nixos-hardware/lenovo/thinkpad/intel.nix:2:24`

I see that the variable is defined in the file `common.nix` but it doesn't look like this file is included in the profile or in  `intel.nix` that uses the variable.

**Comment by zimbatm** [comment]
looks like you broke something @yegortimoshenko

**Comment by yegortimoshenko** [comment]
@Nichlas Fixing right away. Sorry.

**Comment by zimbatm** [comment]
@yegortimoshenko that's what I meant by making changes on hardware you don't own. It happens to the best of us.

**Comment by yegortimoshenko** [comment]
@zimbatm I'll test these profiles next time. I have very similar hardware and honestly none of ThinkPad profiles currently in the tree are specific to any ThinkPad model.

**Comment by yegortimoshenko** [comment]
Also we really need evaluation tests (#7).

**Comment by yegortimoshenko** [comment]
I've also subscribed to this repo and will get a notification on issues. Thanks for pinging me!

**Comment by yegortimoshenko** [comment]
@Nichlas: current `t410` profile uses potentially unstable GPU settings. Could you test it out and tell how stable it is, how's battery life, etc. Thanks!

**Comment by Nichlas** [comment]
Yes, I'm plannig to give it at go.

currently got another error though `error: undefined variable ‘config’ at /nix/var/nix/profiles/per-user/root/channels/nixos-hardware/lenovo/thinkpad/default.nix:6:32
(use ‘--show-trace’ to show detailed location information)`

**Comment by yegortimoshenko** [comment]
Fixed, please update the channel: `sudo nix-channel --update nixos-hardware`.
