### ISSUE TITLE
Provide NVIDIA non PRIME profile

### ISSUE THREAD

**Issue by bryanasdev000** [NixOS/nixos-hardware#338]
I have been using nixos-hardware for quite some time with the common profiles, I have recently changed from an AMD to NVIDIA GPU and the first thing that I did was trying to use the NVIDIA profile, but it expects a PRIME environment, which in my desktop, I do not have.

Would be cool to have a `nixos-hardware/common/gpu/nvidia-nonprime.nix` with:

```
{ lib,  ... }:

{
  # For desktops
  # Non-Optimus mode
  # You need an MXM card
  services.xserver.videoDrivers = lib.mkDefault  [ "nvidia" ];
 
  # For high res tty
  hardware.nvidia.modesetting.enable = lib.mkDefault true;
 
  # Suspend/hibernate
  hardware.nvidia.powerManagement.enable = true;
}
``` 

Will happily do a PR if that's the path.

Ref:

- https://nixos.wiki/wiki/Nvidia
- https://nixos.org/manual/nixos/stable/#sec-x11-graphics-cards-nvidia

**Comment by Mic92** [comment]
@bahaynes @thiagokokada opinions?

**Comment by thiagokokada** [comment]
I don't see why not. I just don't like the name `nvidia-nonprime`, I think maybe it should have been `nvidia` and the old one should be called `nvidia-prime`, however this would break other people configs :disappointed:.

**Comment by bahaynes** [comment]
I think it would make sense. I suspect the reason it hasn’t come up previously is that there aren’t as many common models of desktops using nixos-hardware.

It would be good to move the nvidia files into a folder to match the way we have amd, but that will mean we need to fix the paths in any of the devices that use it currently.

**Comment by bryanasdev000** [comment]
> I don't see why not. I just don't like the name `nvidia-nonprime`, I think maybe it should have been `nvidia` and the old one should be called `nvidia-prime`, however this would break other people configs disappointed.

Well I vote for that, just did not want to refactor something that I can not test lol

**Comment by bryanasdev000** [comment]
> I think it would make sense. I suspect the reason it hasn’t come up previously is that there aren’t as many common models of desktops using nixos-hardware.
> 
> It would be good to move the nvidia files into a folder to match the way we have amd, but that will mean we need to fix the paths in any of the devices that use it currently.

Yeap, also we may need to have more than a `nvidia.nix` (or make an override?) for legacy drivers (legacy_470, legacy_390, legacy_340) and maybe betas?

**Comment by thiagokokada** [comment]
> I think it would make sense. I suspect the reason it hasn’t come up previously is that there aren’t as many common models of desktops using nixos-hardware.
> 
> It would be good to move the nvidia files into a folder to match the way we have amd, but that will mean we need to fix the paths in any of the devices that use it currently.

One proposal:

- Create a new `common/gpu/nvidia` directory, move `common/gpu/nvidia.nix` -> `common/gpu/nvidia/prime.nix` and `common/gpu/nvidia-disable.nix` -> `common/gpu/nvidia/disable.nix`
- Keep the old files, mark them as deprecated, and import the new files respectively
- Add a new `common/gpu/nvidia/default.nix`, that is the non-PRIME profile

WDYT @bryanasdev000 @bahaynes ?

**Comment by bryanasdev000** [comment]
> > I think it would make sense. I suspect the reason it hasn’t come up previously is that there aren’t as many common models of desktops using nixos-hardware.
> > It would be good to move the nvidia files into a folder to match the way we have amd, but that will mean we need to fix the paths in any of the devices that use it currently.
> 
> One proposal:
> 
> * Create a new `common/gpu/nvidia` directory, move `common/gpu/nvidia.nix` -> `common/gpu/nvidia/prime.nix` and `common/gpu/nvidia-disable.nix` -> `common/gpu/nvidia/disable.nix`
> * Keep the old files, mark them as deprecated, and import the new files respectively
> * Add a new `common/gpu/nvidia/default.nix`, that is the non-PRIME profile
> 
> WDYT @bryanasdev000 @bahaynes ?

Sounds like a plan for me, it also leave space if in the future we need a `common/gpu/nvidia/legacy470.nix` with overrides for legacy drivers.

About the possible future refactor, a good `sed` does handle it?

**Comment by bryanasdev000** [comment]
People, if everyone agrees, I can start working on a PR.

**Comment by bahaynes** [comment]
Sounds good to me. I can help with fixing the devices I’ve got.

**Comment by TLATER** [comment]
No idea if github notifications ping on PRs, but I implemented @thiagokokada 's suggestion. Would be happy to see a review, I'd like to use these modules :)
