### ISSUE TITLE
README: convert to Markdown?

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixos-hardware#34]

**Comment by yegortimoshenko** [comment]
I don't want to do that, in all honesty. Org is a better format.

**Comment by rehno-lindeque** [comment]
+1 for sticking to the default convention on github

**Comment by rehno-lindeque** [comment]
Even more confusingly, there is [README.org](https://github.com/NixOS/nixos-hardware/blob/585a13d8b929aba086bed5f1fa3317afd30c39b3/README.org), and elsewhere there is [README.wiki](https://github.com/NixOS/nixos-hardware/tree/585a13d8b929aba086bed5f1fa3317afd30c39b3/apple/macbook-pro/10-1/README.wiki).

**Comment by azazel75** [comment]
Why the link to the Lenovo X1 profile was omitted from the README.md?

**Comment by Mic92** [comment]
I thinks was by accident.

**Comment by Mic92** [comment]
It is markdown now.
