### ISSUE TITLE
Document tuning of swappiness

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixos-hardware#344]
I noticed that the PC configurations default to either low ([10](https://github.com/NixOS/nixos-hardware/blob/4c9f07277bd4bc29a051ff2a0ca58c6403e3881a/common/pc/hdd/default.nix#L5)) or very low ([1](https://github.com/NixOS/nixos-hardware/blob/4c9f07277bd4bc29a051ff2a0ca58c6403e3881a/common/pc/ssd/default.nix#L5)) values of `vm.swappiness`. I don’t know much about this topic so it’s not obvious to me why this default is preferable to the kernel’s.

Can someone who understands the tuning please add an explanatory comment?

Thanks.

**Comment by samueldr** [comment]
> swappiness
> 
> This control is used to define how aggressive the kernel will swap
> memory pages.  Higher values will increase aggressiveness, lower values
> decrease the amount of swap.  A value of 0 instructs the kernel not to
> initiate swap until the amount of free and file-backed pages is less
> than the high water mark in a zone.
> 
> The default value is 60.
> 

https://www.kernel.org/doc/Documentation/sysctl/vm.txt

Basically, it is less likely to pre-emptively swap out stuff when swappiness is low. Generally this is cargo-culted config for reducing wear on SSDs.
