### ISSUE TITLE
Remove references to dezgeg.me

### ISSUE THREAD

**Issue by arkivm** [NixOS/nixos-hardware#352]
The binary cache hosted at http://nixos-arm.dezgeg.me/channel is not longer functional and redirects to a landing page.

**Comment by samueldr** [comment]
List:

 - https://github.com/NixOS/nixos-hardware/search?q=dezgeg

Which gives:

 - https://github.com/NixOS/nixos-hardware/blob/master/raspberry-pi/2/README.org
 - https://github.com/NixOS/nixos-hardware/blob/2a76e1204f3a605f8d8d2f323671e1a295a5246d/inversepath/usbarmory/default.nix#L28-L31

For content to fix.

**Comment by Mic92** [comment]
This has been resolved.
