### ISSUE TITLE
WiFi adapter not found / loading on Surface Book 2 with ZFS root

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixos-hardware#364]
Hello!

As in the title; I can access WiFi from the installer, but not the install itself. I'm trying to install 21.11.

Thank you kindly for the help!

**Comment by Mic92** [comment]
Does this help?

```
{
  hardware.enableRedistributableFirmware = lib.mkDefault true;
}
```

Also check in the output of the `dmesg` command if your wifi driver is missing firmware.

**Comment by Mic92** [comment]
cc @mexisme
Also what is your wifi adapter?
```
$ nix-shell -p inxi --command 'inxi -N'
Network:   Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi
           Device-2: Intel Ethernet I219-V driver: e1000e
```

**Comment by shadowrylander** [comment]
Checked the wifi adapter:
```
Network:   Device-1: Marvell 88W8897 [AVASTAR] 802.11ac Wireless driver: mwifiex_pcie
           Device-2: Marvell Bluetooth and Wireless LAN Composite type: USB driver: btusb
```

**Comment by shadowrylander** [comment]
Oops.

Currently checking the hardware option.

**Comment by shadowrylander** [comment]
Hah! It worked! Thank you so much! Should one of us submit a PR for this?

**Comment by shadowrylander** [comment]
Also, could you do it, if possible? I'm off to sleep now! 😅

**Comment by Mic92** [comment]
Preferable you would do it, since I cannot test it and we would rely on you to test future changes to the profile (right now we often use git blame to find testers)

**Comment by shadowrylander** [comment]
Although, slight issue: you need to manually go in and enter the wifi password with network manager, directly from the settings' security tab of the wifi network. Minor complaint, though, there.

**Comment by shadowrylander** [comment]
Ah; makes sense. I'll submit a PR in the morning, then! Thanks again!

**Comment by mexisme** [comment]
> Preferable you would do it, since I cannot test it and we would rely on you to test future changes to the profile (right now we often use git blame to find testers)

I'm afraid I can't test this, either, but happy to review.

**Comment by shadowrylander** [comment]
And done, @mexisme and @Mic92 !
