### ISSUE TITLE
How to check if I'm running the surface kernel?

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixos-hardware#410]
Hello!

As in the title; the surface kernel version in the build attribute set merely states the Linux kernel version, without something like a `-surface` suffix, such as `5.16.11-surface`. How can I check if I'm actually using the surface kernel?

Thank you kindly for the help!

**Comment by Mic92** [comment]
Sorry for the late response. This might work:

```
ls -la /run/current-system/kernel
```

And if not than this maybe:

```
nix show-derivation /run/current-system/kernel | grep src
```

**Comment by shadowrylander** [comment]
Sorry; I meant from within my `NixOS` config itself!

**Comment by Mic92** [comment]
You can load up your nixos configuration in a nixos repl: https://nixos.wiki/wiki/Nix_command/repl#Examples

**Comment by shadowrylander** [comment]
Ah, yes; that'll have to do. Thanks for all the help!
