### ISSUE TITLE
amd/zen2: create module targetting zen2+ and enable amd-pstate

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-hardware#417]
Apparently some newer AMD laptops have some potential enhancements that I don't think we really enable (and maybe don't have a good way of enabling, I think block-listing acpi-cpufreq for all `common-cpu-amd`  is wrong, for example).

see more: https://www.phoronix.com/scan.php?page=news_item&px=AMD-P-State-How-To

**Comment by FlorianFranzen** [comment]
AFAIK all I had to do to get it working on my machine was to boot with the `amd_pstate=passive` kernel flag.

**Comment by fpletz** [comment]
This has been fixed with #624.
