### ISSUE TITLE
Wifi on Lenovo Thinkpad T14s Gen 1 doesn't work

### ISSUE THREAD

**Issue by Melkor333** [NixOS/nixos-hardware#424]
I'm planning on making an MR to fix the wifi of the `Lenovo Thinkpad T14s Gen 1` because it requires the kernel module `rtw89` and its firmware (similar to the `p14s`).
But the necessary `rtw89` kernel module somehow seems broken for a while (see my issue in nixpkgs repo: https://github.com/NixOS/nixpkgs/issues/177844).

A temporary workaround is to use a Kernel newer than 5.15, which has the kernel module `rtw89` builtin. Just add the following to the `hardware-config.nix` and it should work:

```
boot.kernelPackages = pkgs.linuxPackages_5_18;
hardware.firmware = [ pkgs.rtw89-firmware ];
```

**Comment by Mic92** [comment]
Pull requests are welcome if your workaround still works.
