### ISSUE TITLE
linux-surface kernel upgrade to 6.0

### ISSUE THREAD

**Issue by cor** [NixOS/nixos-hardware#485]
The `linux-surface` kernel has been updated quite a lot

https://github.com/linux-surface/linux-surface/tree/master/patches/6.0

But this repository is lagging behind by 8 months:
https://github.com/NixOS/nixos-hardware/tree/master/microsoft/surface

It would be nice if it could be upgraded, as a lot of important fixes have been made since. such as touch screen and pen support

**Comment by Mic92** [comment]
I think this is solved because 6.1.6 is now available: https://github.com/NixOS/nixos-hardware/issues/523#issuecomment-1404714880
