### ISSUE TITLE
no cpufreq governor available on Asus GA402

### ISSUE THREAD

**Issue by aacebedo** [NixOS/nixos-hardware#516]
Hi,

Just figured out that the cpufreq governors are not available on my ryzen based Asus GA402.
I am on kernel 6.1 and amd-pstate module is builtin. Any idea? 

@K900 do you have this problem too ?

**Comment by K900** [comment]
`schedutil` should be available and what you should be using.

**Comment by K900** [comment]
Fixed in https://github.com/NixOS/nixos-hardware/pull/517.
