### ISSUE TITLE
p14s with 6.1.6 kernel no longer needs `acpi_backlight=none` boot param

### ISSUE THREAD

**Issue by nothingmuch** [NixOS/nixos-hardware#542]
Between kernel 6.1.2 and 6.1.6, disabling acpi_backlight in the boot parameters no longer works correctly, because the thinkpad_acpi module is bypassed:

```
[   12.426855] thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
[   12.477923] thinkpad_acpi: Standard ACPI backlight interface available, not loading native one
```

and consequentially with `acpi_backlight=none`, `/sys/class/backlight` is now empty, and the screen brightness can't be controlled.

I was not yet able to track down the change that led to this being natively supported, sorry.

In my configuration I removed this line:
https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/p14s/amd/gen2/default.nix#L13

and `/sys/class/backlight` now has an `amdgpu_bl10` entry, which is missing when `acpi_backlight=none` is specified.

**Comment by itc-ger** [comment]
I expierenced the same issue. And I can confirm that your suggestion fixes the problem.

Btw. do we need a conditional config depending on the kernel version?
I'm afraid on submitting a pull request with no clue if this will break the system config for many folks 

Maybe @domenkozar , @Mic92 or @sbruder could have a look on this or could give some advice, please?

**Comment by Mic92** [comment]
I would make the kernel flag conditional with `lib.optional (lib.versionAtLeast kernel.version "6.1.6")`. Feel free to open a PR. You would need to test the change in any case.
