### ISSUE TITLE
Surface Pro 5... Kernel panic

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixos-hardware#562]
Kernel panic crash when trying to browse to ext4 samba shares.

Surface pro 5.

**Comment by Mic92** [comment]
Please recreate the issue with more information similar to this issue: https://github.com/NixOS/nixos-hardware/issues/434
otherwise it is not useful.

**Comment by phpcitizen** [comment]
I am sorry if it does not show clear enough? What more details do you need?

Actually this explains everything, just not much wording needed like the link provided. Computer freezes with a kernel panic message and only can force reboot specifically when you cd into a samba share mount.

It is for the rev=44ae00e02e8036a66c08f4decdece7e3bbbefee2 of surface pro package.
