### ISSUE TITLE
Support for Dell Precision 3541

### ISSUE THREAD

**Issue by anstylian** [NixOS/nixos-hardware#614]
I want to use Nix-Os on a Dell Precision 3541 which is not added in nixos-hardware yet. 
I will open an MR following this issue, which partially supports this laptop. I will be waiting for your comments. 
Missing from the MR: NVIDIA enable configuration. The laptop has a Quatro P620 NVIDIA card which is not supported by the latest NVIDIA driver.

**Comment by Mic92** [comment]
There are also some older nvidia drivers in nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nvidia-x11/default.nix
