### ISSUE TITLE
Lenovo Legion 5 Pro 16ach6h breaks when using modesetting with current config

### ISSUE THREAD

**Issue by 4JX** [NixOS/nixos-hardware#628]
Opening this up to see how to go about fixing it.

The commit https://github.com/NixOS/nixos-hardware/commit/630a8e3e4eea61d35524699f2f59dbc64886357d switched the default AMD driver from `amdgpu` to `modesetting`. When updating past this commit Xorg does not boot up correctly on my machine in hybrid/offload mode: https://gist.github.com/4JX/37d35bf95970f96ad341658da7af0ecd, with the Xorg config that is created being https://gist.github.com/4JX/ec3b37198fdc5900ac258ca99ce0e068.

If I manually remove the layout/device/screen referencing `amdgpu` (Created due to the presence of `hardware.nvidia.prime.amdgpuBusId`. Where any duplicate entries for drivers, from both `amdgpu` or `modesetting`, that will eventually end up controlling the iGPU trigger this issue if at least one of them uses the `modesetting` driver.) and move the `BusID` to the modesetting section (not necessary, there for redundancy) it boots up just fine.

I'm not sure if a proper fix would be to just tell it to use the `amdgpu` driver for my device, as it seems that the NixOS option is also to blame (it only considers modesetting for [intel cards](https://github.com/NixOS/nixpkgs/blob/0b530a72bd17b3cb83923f3d3e1165726902a78b/nixos/modules/hardware/video/nvidia.nix#L247) despite the move towards ditching the other drivers https://github.com/NixOS/nixpkgs/pull/218437).

**Comment by Malix-Labs** [comment]
@4JX #841 are we sure this is still relevant to be kept?

I don't think it's the case anymore

**Comment by 4JX** [comment]
Could be the case, haven't tweaked the base configs around in a while out of "just works" convenience.

**Comment by Malix-Labs** [comment]
When I tried, it seemed to be the case indeed

I submitted #2002 about it
