### ISSUE TITLE
Support for Libretech devices

### ISSUE THREAD

**Issue by nosewings** [NixOS/nixos-hardware#679]
Hi,

I've done a bit of work compiling the [Libretech Linux kernel](https://github.com/libre-computer-project/libretech-linux) on NixOS. If it's welcome, I can submit a PR for adding it to this repo.

**Comment by Mic92** [comment]
We already have a bunch of other kernels. So why not.

**Comment by Mic92** [comment]
Ok. Nothing actionable in this PR. The offer still stands.
