### ISSUE TITLE
Fixing audio on Macbook Pro 14,1 using snd_hda_macbookpro

### ISSUE THREAD

**Issue by not-ivy** [NixOS/nixos-hardware#688]
[Audio is not a lost cause 😄](https://github.com/NixOS/nixos-hardware/pull/486)

A (partial) solution can be found here: https://github.com/davidjo/snd_hda_macbookpro

**Comment by Guanran928** [comment]
+1, no audio on my iMac 2017 (Cirrus Logic CS8409)...
I was using [this](https://github.com/egorenar/snd-hda-codec-cs8409) (kernel module? don't really know what is it called) on Fedora Workstation, but I have no idea how to install it on NixOS...

**Comment by Guanran928** [comment]
@Mic92 PR merged, closing?
