### ISSUE TITLE
tests: evaluate master and PRs

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixos-hardware#7]
Would be nice to automatically check that PRs are syntatically correct.

**Comment by yegortimoshenko** [comment]
Now evaluation can be checked by running `tests/eval-test.sh`:

https://github.com/NixOS/nixos-hardware/tree/f35389f4690e297c8f3cc0229f213aaaecc882b1/tests

The only thing left is to have a bot do it on pull requests. This test requires NixOS.

**Comment by yegortimoshenko** [comment]
I think we should evaluate `master` as well.

**Comment by yegortimoshenko** [comment]
@zimbatm fixed this in #40. Thank you a lot! See #42 and #43 for examples.
