### ISSUE TITLE
Please add comments explaining the configuration settings (from now on)

### ISSUE THREAD

**Issue by giorgiga** [NixOS/nixos-hardware#738]
Could you make a rule about annotating all settings with an explanation?

Eg. I was trying to understand why `services.xserver.libinput.enable` defaults to `true` in `common/pc/default.nix` (*) and had  to read the relevant nixpkgs sources to find out.

_(*) well, actually I was trying to figure out whether I should turn it off on my headless server. BTW the answer is "yes"_

**Comment by Mic92** [comment]
Noted.
