### ISSUE TITLE
How about Dell Precision 7530?

### ISSUE THREAD

**Issue by meicale** [NixOS/nixos-hardware#739]
Which is a better config for Dell Precision 7530. If no, Would you mind adding one? Thx

**Comment by Mic92** [comment]
Sorry. We do not have the hardware to make or test this configuration. This repository is driven by it's contributors. So if you have configuration for this device that you have tested, feel free to make a pull request.

**Comment by Mic92** [comment]
A good starting point is to import a NixOS model for the CPU. You can also check if the archlinux wiki has an article on the hardware that describes what specific quirks are required to make it run.
