### ISSUE TITLE
Rename Omen Laptop Model (Breaking)

### ISSUE THREAD

**Issue by sjcobb2022** [NixOS/nixos-hardware#753]
As mentioned in #748

It may be a good idea to update the naming schema for the omen-en00015p. en00015p is not reflective of the model name of any omen product that I can find.

Most likely, the product ID is referring to [this](https://support.hp.com/us-en/product/details/omen-15-en0000-laptop-pc-series/model/35335114) model of HP omen laptop.

All other omen laptop models are in reference to the model name.

**Comment by Mic92** [comment]
This was added in https://github.com/NixOS/nixos-hardware/pull/457

**Comment by Mic92** [comment]
cc @celsomiranda

**Comment by celsomiranda** [comment]
You're right.

The correct model is 15-en0002np.
I'll fix this as soon as possible.

Jörg Thalheim ***@***.***> escreveu no dia sexta, 6/10/2023
à(s) 19:51:
