### ISSUE TITLE
Support for peripheral devices? 

### ISSUE THREAD

**Issue by cbleslie** [NixOS/nixos-hardware#785]
:wave: Hello everyone!

I have one or two peripheral devices I would like to make modules for. The only problem is that `nixos-hardware` seems to be about; "the whole computer." is there room in this repo for individual "brand" peripherals?

This snippet would be the first thing converted to a module. It's for Apples External Super-drive:
https://gitlab.com/-/snippets/3623394

Thanks for your time!

**Comment by ulrikstrid** [comment]
Shouldn't this go into `nixpkgs` as a service instead?

**Comment by cbleslie** [comment]
@ulrikstrid ,
This was my first thought. One could say the same thing for `nixos-hardware` repo as well right? Where is the line drawn? If the contribution is not welcome here, that's fine. I can focus on putting it in `nixpkgs`.

**Comment by cbleslie** [comment]
Much clearer. Thank you.
