### ISSUE TITLE
Request to add `msi-ec` for certain MSI laptops (eg. GF75-Thin-9SC)

### ISSUE THREAD

**Issue by TheArcaneBrony** [NixOS/nixos-hardware#790]
Module can be found here: https://github.com/BeardOverflow/msi-ec
Adds interfaces for eg. controlling fan speed (including cooler boost), swapping fn/super, firmware webcam toggle, different firmware power modes (power saving/normal/overclocked), etc.

**Comment by Mic92** [comment]
Feel free to make a pull request. It's unlikely that someone will add this purely on this issue. It's also hard to test without having the hardware. If they need this feature themselves, the don't need to have an issue either.
