### ISSUE TITLE
Lenovo Yoga Pro 7 14APH8 

### ISSUE THREAD

**Issue by dandanua** [NixOS/nixos-hardware#799]
I have Lenovo Yoga Pro 7 14APH8 with AMD 7840HS CPU.  

My issue was that I couldn't resume it from sleep - I had disk IO error as described [here](https://discourse.nixos.org/t/couldnt-resume-from-suspend-on-btrfs/36968/2).

I was able to fix it by 
`boot.kernelParams = [ “amd_iommu=off” “iommu=soft” ]`

This probably should be added to the list.

**Comment by Dirtyyt66** [comment]
# - [ ] ~~~~

**Comment by Mic92** [comment]
Sounds good. Maybe it should be configurable for people that need iommu for things like virtualization.

**Comment by Mic92** [comment]
Feel free to open a pull request.
