### ISSUE TITLE
Fix for framework 13 AMD white screen / flickering issue on kernels >6.1

### ISSUE THREAD

**Issue by RichardJActon** [NixOS/nixos-hardware#817]
I was encountering an issue with my screen flickering white, especially after resume from sleep and did some searching and found a solution that I think it would be good to have added to the framework 13 AMD config here.

I'm still pretty new to nix lang and this is my first issue on this project so I'm not quite sure how best to implement this.

```
# if using this or any version >6.1
boot.kernelPackages = pkgs.linuxPackages_latest;
# then this is needed to stop the flickering issue
boot.kernelParams = ["amdgpu.sg_display=0"];
```

Sources:

https://blabli.blog/post/2023/03/14/nixos-amd-raphael-igpu-screen-issues/

https://discourse.nixos.org/t/white-flickering-desktop-environments-with-amd-raphael-ryzen-7950x/26286/3

**Comment by Mic92** [comment]
I think the kernel params option would go here: https://github.com/NixOS/nixos-hardware/blob/master/framework/13-inch/7040-amd/default.nix
We already set linux kernel to latest to bump it to bigger than linux 6.1.

**Comment by Luflosi** [comment]
I created #866 to fix this.
