### ISSUE TITLE
Framework 16 Support

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixos-hardware#859]
Now that the Framework 16 is shipping, it makes sense to add a profile for it as well :3

**Comment by CodeMichael** [comment]
I have my FW16 and would be happy to contribute. If there are submission guidelines that I can review please point them out to me.

**Comment by nyabinary** [comment]
> I have my FW16 and would be happy to contribute. If there are submission guidelines that I can review please point them out to me.

I recommend just looking at the Framework folder and copy the style/semantics of that and if you have any other question ask it in the Matrix chat :)

**Comment by Flameopathic** [comment]
@nyabinary ^^
