### ISSUE TITLE
Nixos-rebuild fails after adding this 

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixos-hardware#89]
When following the README to add this repo as a channel, I get the following error at the next `nixos-rebuild switch`:

    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
    error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
    building Nix...
    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
    error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)
    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
    error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
    /tmp/nixos-rebuild.Oj5CEO/nix
    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
    error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
    building the system configuration...
    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
    error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)

This is consistently the case for me. It does not seem to happen, if I add the channel with a name not starting with `nixos`

**Comment by kalbasit** [comment]
What's the output of `nixos-channel --list` as well as `sudo -i nixos-channel --list`?

Did you run `sudo -i nixos-rebuild switch` or did you forget the `-i`?

**Comment by yegortimoshenko** [comment]
Alternatively, you can set channels as root (`sudo nix-channel --add ...`) and then rebuild as root without `-i` (`sudo nixos-rebuild switch`).

**Comment by neumantm** [comment]
> What's the output of `nix-channel --list` as well as `sudo -i nix-channel --list`?

I don't have the exact output now, but `sudo -i nix-channel --list` looked fine (Just the normal nixos channel and nixos-hardware) and `nix-channel --list` should have been producing an empty output. (At least it does now)

> Did you run `sudo -i nixos-rebuild switch` or did you forget the `-i`?
No I didn't use `-i` as did not know it was necessary. I never do it that way. Should I?

Sadly as I just now tried to reproduce this, all worked ...
5 days ago I confirmed multiple times, and each time the same problem occured.
Could it have been something with the network?

**Comment by sgraf812** [comment]
I'm having the same problems on a fresh NixOS install. Output of `nix-channel --list`:

```
nixos https://nixos.org/channels/nixos-19.03
nixos-hardware https://github.com/NixOS/nixos-hardware/archive/master.tar.gz
```

I'm still running everything as root as I set up my machine, so no need for `sudo -i`.

FWIW, /nix/var/nix/profiles/per-user/root/channels/nixos really doesn't exist (its parent and /nix/var/nix/profiles/per-user/root/channels/nixos-hardware does, though).

**Comment by sgraf812** [comment]
OK, I figured it out. Apparently, I never ran `nix-channel --upgrade` before, so there was no clone of `nixos` yet in said path. `nixos-rebuild switch` finished succesfully now.

**Comment by aaronchall** [comment]
I found I needed `sudo -i nixos-rebuild switch --upgrade` Perhaps the docs should be updated to add `sudo -i` for the examples? I think that I've been doing it the wrong way all this time (just `sudo`), but it seems to have been working.

**Comment by jonringer** [comment]
most likely an issue with your nix channels. ensure that `sudo nix-channel --list` displays a channel, if not, then you will have to add one.

**Comment by Mic92** [comment]
I think the default `sudo` should work. There must be something else wrong. Closing this for now. 
I currently don't see what we can fix from nixos-hardware perspective.
