### ISSUE TITLE
disabling ALS is no longer necessary, nor a desired default for some users

### ISSUE THREAD

**Issue by taotien** [NixOS/nixos-hardware#894]
https://github.com/NixOS/nixos-hardware/blob/1e679b9a9970780cd5d4dfe755a74a8f96d33388/framework/13-inch/12th-gen-intel/default.nix#L19

On my system the keys work fine, so I'm assuming at some point the kernel was patched to fix the conflict between the ALS and keyboard buttons. I am on nixos-unstable, kernel is currently 6.8.1.

I'm unsure how to override parts of a module, but my suggestion is to make enabling and disabling ALS or buttons an optional feature, and unnecessary past a certain kernel version.

**Comment by Mic92** [comment]
Ok. Feel free to make a pull request that removes this line and we can ping people who are using it.
