### ISSUE TITLE
network dns error  

### ISSUE THREAD

**Issue by et2300** [NixOS/nixos-hardware#911]
i am in qemu dns not really but i in centos
 dns is really

**Comment by et2300** [comment]
@Lyndeno

**Comment by Mic92** [comment]
Sorry, this repository is about NixOS, not CentOS.

**Comment by et2300** [comment]
![Screenshot_2024-04-13-15-46-08-55_84d3000e3f4017145260f7618db1d683](https://github.com/NixOS/nixos-hardware/assets/81605900/f7a55e62-19ee-4210-9d18-2351d5065dae)

**Comment by et2300** [comment]
![Screenshot_2024-04-13-15-45-16-58_84d3000e3f4017145260f7618db1d683](https://github.com/NixOS/nixos-hardware/assets/81605900/97d044ee-bd39-4e4b-bc90-f413aff3de05)

**Comment by et2300** [comment]
@Mic92

**Comment by et2300** [comment]
![Screenshot_2024-04-14-13-29-07-86_84d3000e3f4017145260f7618db1d683](https://github.com/NixOS/nixos-hardware/assets/81605900/66853226-c31f-44f5-bf86-8e0c166a9696)

**Comment by et2300** [comment]
![Screenshot_2024-04-14-13-41-44-75_8659c1e795b4b4239e38d87c88c077b3](https://github.com/NixOS/nixos-hardware/assets/81605900/7de5542a-0d46-4a85-a630-640f2193a168)
