### ISSUE TITLE
network dns error

### ISSUE THREAD

**Issue by et2300** [NixOS/nixos-hardware#913]
![Screenshot_2024-04-14-13-29-07-86_84d3000e3f4017145260f7618db1d683](https://github.com/NixOS/nixos-hardware/assets/81605900/77741368-09e9-4a06-be39-b85431956eac)
![Screenshot_2024-04-14-13-41-44-75_8659c1e795b4b4239e38d87c88c077b3](https://github.com/NixOS/nixos-hardware/assets/81605900/a3ce8c6f-0032-483e-b865-90242355e909)

**Comment by SuperSandro2000** [comment]
Wrong repo and termux is known to have wonky DNS.

**Comment by et2300** [comment]
thus is start qemu command 
`qemu-system-x86_64 -hda  nixos.vmdk -cdrom /storage/emulated/0/Download/latest-nixos-minimal-x86_64-linux.iso -boot d -m 8g -netdev user,id=n1,hostfwd=tcp::2222-:22,dns=223.5.5.5 -device e1000,netdev=n1 -vnc :1 -monitor stdio`

**Comment by et2300** [comment]
@everyone
