### ISSUE TITLE
Desktop profile?

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixos-hardware#914]
Would it make sense to have a desktop profile in addition to the laptop one? For example, I ended up adding the following to stop GNOME from alerting that it was going to put my machine to sleep when inactive, despite never actually doing so:

```nix
{config}: {
  config.programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/gnome/settings-daemon/plugins/power" = {
          sleep-inactive-ac-type = "nothing";
        };
      };
    }
  ];
}
```

**Comment by samueldr** [comment]
Anything "desktop" would likely end-up *too* opinionated for this repo, I believe.

(Also there may be some complex legal/compliance issues with defaults not putting systems to sleep in some locales...)
