### ISSUE TITLE
Gigabyte b550 as nixosModule to use in flake installation

### ISSUE THREAD

**Issue by gbrls** [NixOS/nixos-hardware#926]
Hi, I want to use the `gigabyte/b550` module from a flakes install. If the `flake.nix` file in this repo updates to include this module inside the `nixosModules` output, will it work or is there extra work needed?

I'm glad to help any way that I can, just new to nix and not sure how to do that.

**Comment by matdibu** [comment]
Yeah, just open a PR and add it to this repo's `flake.nix`, then you can use it normally.

The fact that it's missing might have been an oversight, but I'm not sure.

**Comment by Mic92** [comment]
Done https://github.com/NixOS/nixos-hardware/pull/978/files
