### ISSUE TITLE
Missing documentation: Common Hardware

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixos-hardware#935]
Could you please provide some documentation about using scripts under `common`:
https://github.com/NixOS/nixos-hardware/tree/master/common

It is not clear how multiple `common` configs should be imported, if the laptop model is not listed..
Like for example, how should my config look like, if I have a "noname" laptop, with intel and nvidia, and I want to activate all intel features and say disable the nvidia card completely. And what should I change to enable "Optimus PRIME" or maybe work with nvidia only..

Some examples with and without using `Home Manager` would be great.

**Comment by Mic92** [comment]
Please don't consider `common` a public api. We will upstream and remove modules over time without any warning or deprecation notice. You can add your laptop module to this repository and import the modules needed for it. I.e. you can look at how other laptop models similar to yours do it.
