### ISSUE TITLE
Build unstable kernel for VisionFive 2

### ISSUE THREAD

**Issue by onny** [NixOS/nixos-hardware#950]
Hey,

I'm trying to build the latest unstable kernel for Starfive VisionFive 2 kernel. I git cloned the nixos-hardware-repository and changed revision and hash in `starfive/visionfive/v2/linux-6.6.nix`

```
      src = fetchFromGitHub {
        owner = "starfive-tech";
        repo = "linux";
        rev = "430c94788670c08f6b28c8253c62214da5d942a1";
        hash = "sha256-EfccTNP8OLj0pvpBlftgPyXvTi6EJVuciVwyRsYatTk=";
      };
```

Unfortunately don't know how to do this via overlays.

I added my local nixos-hardware fork to the flake which defines my system (following this tutorial https://wiki.nixos.org/wiki/NixOS_on_RISCV/VisionFive_2 ). When trying to build I get this error

```
       >     [CC]     raid/x86.o
       >     [CC]     raid/x86z.o
       >     [SED]    fsck/bcachefsck_all
       >     [SED]    fsck/bcachefsck_fail@.service
       >     [SED]    fsck/bcachefsck@.service
       >     [SED]    fsck/bcachefsck_all_fail.service
       >     [SED]    fsck/bcachefsck_all.service
       >     [AR]     libbcachefs.a
       > /nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: ar: command not found
```

Is it related to cross compiling or is "binutils" with "ar" missing somewhere?

**Comment by malteneuss** [comment]
Cross-compiling seems to be a lot of luck. I can't even get the current linux kernel to build :(

Have you tried using your visionfive2 board as a remote builder to do native compiling instead? I tried it the Rapsberry Pi 5 and went quite well. I will try that as well for the Visionfive2.

Btw, do you know the status or a tracking page of starfive patches in the upstream Linux kernel and maybe UEFI or u-boot? As far as i understand the nixpkgs maintainers don't want to add custom linux kernels and firmwares anymore as that apparently was too much maintenance overhead in the past. Would be great know when NixOS will run out of the box.
