### ISSUE TITLE
Lenovo Legion 15ACH6H is missing from flake.nix and README.md 

### ISSUE THREAD

**Issue by ssouthcity** [NixOS/nixos-hardware#953]
Hello!

I am using 15ACH6H as my daily driver, and I noticed that there is a configuration dir for the device in lenovo/legion/15ach6h, but this is not listed in the nix flake. I tracked it back to #887, but I am unsure about why this was merged without being properly added to the flake.

**Comment by ssouthcity** [comment]
I've opened a [PR](https://github.com/NixOS/nixos-hardware/pull/959) to fix this issue

**Comment by yuannan** [comment]
Sorry about this :/ I've been extremely busy with work and I didn't check my GitHub until now (I usually use GitLab). Thanks for your fix :)
