### ISSUE TITLE
[amdgpu.amdvlk] Options conflict with nixpkgs-unstable

### ISSUE THREAD

**Issue by higherorderfunctor** [NixOS/nixos-hardware#981]
`hardware.amdgpu.amdvlk` was added with https://github.com/NixOS/nixpkgs/commit/7082d01967a175edff2d312fc6138878c8f409aa.

The options clash requiring either not using `inputs.nixos-hardware.nixosModules.common-gpu-amd` or possibly disabling the nixpkgs module (haven't tested).  This commit adds additional attributes which conflict with this package's enable option.

```nix
  hardware = {
    amdgpu.amdvlk = {
      enable = true;
      supportExperimental.enable = true;
      settings = {
        AllowVkPipelineCachingToDisk = 1; # ~/.cache/AMD/VkCache
        ShaderCacheMode = 1;
        IFH = 0;
        EnableVmAlwaysValid = 1;
        IdleAfterSubmitGpuMask = 1;
      };
    };
  };
```

**Comment by Mic92** [comment]
Please update nixos-hardware. This has been fixed in https://github.com/NixOS/nixos-hardware/pull/977
