### ISSUE TITLE
Add support for dual graphics nvidia intel on System76 Gazelle  

### ISSUE THREAD

**Issue by matteobongio** [NixOS/nixos-hardware#982]
Hello, I have a System76 Gaze18 with dual graphics, I saw that there is support for the darp6, but not the gazelle. I have spent the last couple of days trying to get everything to work, currently vulkan is not working for some reason.

Here is my config [github](https://github.com/matteobongio/nixos/tree/46542fdc6902f1cd7a5055b63eb3505b5afc2802)

[nixos discourse thread](https://discourse.nixos.org/t/vulkan-not-working-with-nvidia-drivers/46972)

**Comment by Mic92** [comment]
Feel free to make a pull request with your progress.
