### ISSUE TITLE
Enable intel-media-driver?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixos-hardware#99]
cc: @yegortimoshenko 

Today I leaned that there is another driver from Intel that works with libva for accelerated video.

IF you add `intel-media-driver` to opengl packages, you can do this
`LIBVA_DRIVER_NAME=iHD vainfo` and see that a different driver is being used.

I don't really understand the pro/cons or any differences between using i965 and iHD, but I wanted to mention it since it doesn't seem widely documented/known.

I documented this on the related wiki page: https://nixos.wiki/wiki/Accelerated_Video_Playback

**Comment by colemickens** [comment]
I don't see any reason to not include this. AFAICT it's always going to require the user to opt in for it to be prioritized over i915. I'll send a PR.

**Comment by asymmetric** [comment]
@colemickens did you eventually create the PR?
